### ISSUE TITLE
IRC Profiles: Big/All etc...

### ISSUE THREAD

**Issue by ghost** [artix-linux/iso-profiles#16]
Hello,

Would it be possible to sort the profiles a bit or add descriptions?

And, even more importantly to me, could you guys also add a "big" .iso? This could be distributed via torrent, a bit similar how slackware DVD works (I am using slackware right now, it's great, init freedom - I want to give artix a try but I am a very old and very lazy linux user so I'd prefer a big fat DVD with lots of stuff included by default.)

The current iso-profiles has no readme to explain much unfortunately. I understand that it is aimed towards advanced linux users; I may qualify for this, having used linux since almost 15 years, but I am
also notorious lazy, sorry. :)

**Comment by udeved** [comment]
>Would it be possible to sort the profiles a bit or add descriptions?

For what? The profile name is the desktop that will be installed on iso.

>And, even more importantly to me, could you guys also add a "big" .iso?

Nope, this is counterproductive to a rolling release, plus, our iso is all netinstall.

> I may qualify for this, having used linux since almost 15 years, but I am
also notorious lazy, sorry. :)

Your laziness will likely prevent you from using artix, since laziness leads to being angered in computer world.

**Comment by cromerc** [comment]
I am going to close this due to age. Feel free to comment if there is any more info to add or open another issue.
